export const introText = 'O espaço urbano evoluiu muito durante a história, passando por vários estágios e evoluções até chegar às cidades modernas que conhecemos hoje. Este site abrange a história geral destes espaços do ponto de vista ocidental, e eventualmente global, de forma breve e dinâmica. Todos os estágios descritos terão uma cidade como exemplo para aprofundamento, ela nem sempre foi a maior ou mais influente, mas sim a mais interessante para o contexto do período.';

export const antigasCivText = {
    pageOne: 'O surgimento do espaço urbano está diretamente ligado à sedentarização da humanidade, que ocorreu após a revolução agrícola, dez mil anos antes de Cristo. Porém, esses espaços somente começaram a crescer por volta de seis a sete mil anos após essa revolução, em formas de pequenas aldeias. Elas se concentraram em focos principalmente em volta de terras férteis e rios, dando origem aos grandes berços da civilização. Esses berços se foram o rio Nilo (Egito), rios Tigre e Eufrates (Mesopotâmia), rio Indo (Índia) e rio Amarelo (China). Nestas pequenas aldeias foram desenvolvidos governos, escritas, metalurgia, além de diversas culturas e costumes. Essas aldeias eventualmente cresceram e evoluíram para se tornar cidades, sendo as mais relevantes Alexandria, Atenas, Cartago, e a mais importante, Roma.',
    pageTwo: 'Roma foi fundada às margens do rio Tibre, nas planícies de Latium, localizada na península Itálica. O mito da criação de roma diz que dois irmãos descendentes do herói de Tróia Enéas, Rômulo e Remo, foram jogados no rio pelo usurpador Amúlio. Os irmãos foram amamentados por uma loba, e cresceram com a missão de conseguir vingança. Após conseguir sua vingança, Rômulo matou o irmão e se tornou o primeiro rei de Roma. Na realidade, a cidade foi formada por uma união de aldeias latinas em volta do rio, por volta de 573 a.C. A cidade-Estado foi se expandindo, se tornando uma república e depois um império, que no seu auge cobria todas as terras banhadas pelo mar Mediterrâneo, Mare Nostrum. A expansão da sociedade romana também proporcionou a ascensão de espaços urbanos em seus territórios, o que chegou a ser a maior parte do mundo ocidental. Assim, surgiram as primeiras redes urbanas com múltiplos núcleos populacionais conectados e Roma mesmo chegou a ter mais de 900 mil habitantes no início da era Cristã. O período romano foi o auge urbano da antiguidade, e a queda do Império Ocidental marcou um grande declínio desses espaços que demoraram para se recuperar.'
};

export const idadeMediaText = {
    pageOne: 'A Idade Média é um grande vale em questão de urbanização na Europa e tudo tem a ver com o sistema quase sinônimo de idade média europeia, feudalismo. Após a queda de Roma e as invasões bárbaras, muitas pessoas migraram das cidades, que estavam sob constante invasão de tribos germânicas, para o meio rural. Estas terras estavam sob controle descentralizado de vários donos que estabeleceram feudos, se tornando senhores feudais. Todos os trabalhadores se tornaram servos, completamente subjugados ao senhor feudal, que também é submetido a um suserano. Assim a hierarquia de poder se tornou uma complexa rede de suseranos e vassalos extremamente autônomos. Com outros abalos como a peste bubônica, as populações nas cidades não se comparam ao ápice da idade antiga. Apenas no final da idade média que o espaço urbano volta a ressurgir com o surgimento da burguesia. Uma cidade que pode ser considerada vanguarda nesse quesito é Veneza, que começa a se destacar pelo comércio antes que o resto do continente.',
    pageTwo: 'A Sereníssima República de Veneza, como era chamada no auge, surgiu primeiramente como um vilarejo de pescadores na Laguna de Veneza. A região fazia parte do Império Bizantino, e a cidade se originou com a mudança da sede do duque bizantino para as ilhas lagunenses. Porém, nessa época,  século VIII, o poder de Constantinopla já não era forte sobre a futura potência marítima. Basicamente independente, por volta do ano 1000, a república expulsou piratas do mar Adriático e começou seu domínio comercial e marítimo sobre o mediterraneo. Veneza estrategicamente manteve relações comerciais com os bizantinos e enriqueceu com o comércio de especiarias do oriente a partir do Levante. No ápice, a Sereníssima República chegou a conquistar territórios sobre todo o mar Adriático e leste Mediterraneo, destaques sendo a Istria, Dalmácia, Creta, outros territórios gregos, e até o Chipre. Com toda essa prosperidade, a cidade de Veneza se expandiu muito, e se tornou um dos principais, se não o principal porto do mundo na época. Com a queda de Constantinopla em 1453, os Otomanos impuseram grandes restrições comerciais, iniciando o declínio da república mercantil, que é finalizado com o descobrimento de novas rotas comerciais por volta do continente africano.'
};













