export const introText = 'O espaço urbano evoluiu muito durante a história, passando por vários estágios e evoluções até chegar às cidades modernas que conhecemos hoje. Este site abrange a história geral destes espaços do ponto de vista ocidental, e eventualmente global, de forma breve e dinâmica. Todos os estágios descritos terão uma cidade como exemplo para aprofundamento, ela nem sempre foi a maior ou mais influente, mas sim a mais interessante para o contexto do período.';

export const antigasCivText = {
    pageOne: 'O surgimento do espaço urbano está diretamente ligado à sedentarização da humanidade, que ocorreu após a revolução agrícola, dez mil anos antes de Cristo. Porém, esses espaços somente começaram a crescer por volta de seis a sete mil anos após essa revolução, em formas de pequenas aldeias. Elas se concentraram em focos principalmente em volta de terras férteis e rios, dando origem aos grandes berços da civilização. Esses berços se foram o rio Nilo (Egito), rios Tigre e Eufrates (Mesopotâmia), rio Indo (Índia) e rio Amarelo (China). Nestas pequenas aldeias foram desenvolvidos governos, escritas, metalurgia, além de diversas culturas e costumes. Essas aldeias eventualmente cresceram e evoluíram para se tornar cidades, sendo as mais relevantes Alexandria, Atenas, Cartago, e a mais importante, Roma.',
    pageTwo: 'Roma foi fundada às margens do rio Tibre, nas planícies de Latium, localizada na península Itálica. O mito da criação de roma diz que dois irmãos descendentes do herói de Tróia Enéas, Rômulo e Remo, foram jogados no rio pelo usurpador Amúlio. Os irmãos foram amamentados por uma loba, e cresceram com a missão de conseguir vingança. Após conseguir sua vingança, Rômulo matou o irmão e se tornou o primeiro rei de Roma. Na realidade, a cidade foi formada por uma união de aldeias latinas em volta do rio, por volta de 573 a.C. A cidade-Estado foi se expandindo, se tornando uma república e depois um império, que no seu auge cobria todas as terras banhadas pelo mar Mediterrâneo, Mare Nostrum. A expansão da sociedade romana também proporcionou a ascensão de espaços urbanos em seus territórios, o que chegou a ser a maior parte do mundo ocidental. Assim, surgiram as primeiras redes urbanas com múltiplos núcleos populacionais conectados e Roma mesmo chegou a ter mais de 900 mil habitantes no início da era Cristã. O período romano foi o auge urbano da antiguidade, e a queda do Império Ocidental marcou um grande declínio desses espaços que demoraram para se recuperar.'
};

export const idadeMediaText = {
    pageOne: 'A Idade Média é um grande vale em questão de urbanização na Europa e tudo tem a ver com o sistema quase sinônimo de idade média europeia, feudalismo. Após a queda de Roma e as invasões bárbaras, muitas pessoas migraram das cidades, que estavam sob constante invasão de tribos germânicas, para o meio rural. Estas terras estavam sob controle descentralizado de vários donos que estabeleceram feudos, se tornando senhores feudais. Todos os trabalhadores se tornaram servos, completamente subjugados ao senhor feudal, que também é submetido a um suserano. Assim a hierarquia de poder se tornou uma complexa rede de suseranos e vassalos extremamente autônomos. Com outros abalos como a peste bubônica, as populações nas cidades não se comparam ao ápice da idade antiga. Apenas no final da idade média que o espaço urbano volta a ressurgir com o surgimento da burguesia. Uma cidade que pode ser considerada vanguarda nesse quesito é Veneza, que começa a se destacar pelo comércio antes que o resto do continente.',
    pageTwo: 'A Sereníssima República de Veneza, como era chamada no auge, surgiu primeiramente como um vilarejo de pescadores na Laguna de Veneza. A região fazia parte do Império Bizantino, e a cidade se originou com a mudança da sede do duque bizantino para as ilhas lagunenses. Porém, nessa época,  século VIII, o poder de Constantinopla já não era forte sobre a futura potência marítima. Basicamente independente, por volta do ano 1000, a república expulsou piratas do mar Adriático e começou seu domínio comercial e marítimo sobre o mediterraneo. Veneza estrategicamente manteve relações comerciais com os bizantinos e enriqueceu com o comércio de especiarias do oriente a partir do Levante. No ápice, a Sereníssima República chegou a conquistar territórios sobre todo o mar Adriático e leste Mediterraneo, destaques sendo a Istria, Dalmácia, Creta, outros territórios gregos, e até o Chipre. Com toda essa prosperidade, a cidade de Veneza se expandiu muito, e se tornou um dos principais, se não o principal porto do mundo na época. Com a queda de Constantinopla em 1453, os Otomanos impuseram grandes restrições comerciais, iniciando o declínio da república mercantil, que é finalizado com o descobrimento de novas rotas comerciais por volta do continente africano.'
};

export const idadeModernaText = {
    pageOne: 'Após a Idade Média, a classe burguesa já estava concretizada nas cidades europeias, até que a próxima palavra-chave tomou posse na Idade Moderna, mercantilismo. Esse em si tem quatro outras palavras-chave: protecionismo, balança comercial favorável, metalismo e monopólio.',
    listPoints: ['Protecionismo', 'Balança comercial favorável', 'Metalismo', 'Monopólio'],
    listContent: [
        'Intervenção estatal forte na economia com o intuito de preservar e cultivar o mercado interno utilizando-se de tarifas, regulamentações, bloqueios e mais.',
        'Quando um país exporta produtos do que importa, em teoria deixando mais riquezas dentro do país.',
        'Doutrina européia da Idade Moderna que dizia que a riqueza de uma nação é medida na quantidade de metais preciosos que ela possui. Grande impulsionador da colonização das Américas, já que os europeus vieram loucos à procura de ouro.',
        'Direito dado pelo Estado a certos membros da burguesia de comercialização/produção de uma certa mercadoria. Tinha o intuito de acumular fortunas mais rapidamente. Extremamente presente nas colônias como forma de direcionar riquezas à metrópole.'
    ],
    pageOne2: 'Todas elas estão relacionadas ao contexto de escassez de metais na Europa além do surgimento de Estado-Nações, com poder muito mais centralizado, podendo chegar a ser absolutista. Essa grande concentração de riquezas e poder levou ao rápido desenvolvimento das capitais dos grandes impérios, que tinham recursos do mundo inteiro levados para construção de casas e palácios ornamentados e luxuosos. Alguns centros urbanos passaram a ter ainda mais relevância do que já tinham antes, como Paris, e outros se tornaram muito importantes nessa época, como Lisboa.',
    pageTwo: 'Com a queda de Roma Oriental, as rotas comerciais terrestres com as Índias foram barradas, criando a demanda para uma nova rota comercial. Assim, começaram as grandes navegações, que estabeleceram colônias pelo mundo todo que extraiam ou compravam recursos para suas metrópoles. Isso era um trabalho complexo, sendo necessário muitas tecnologias marítimas, exposição ao oceano e um Estado-Nação moderno, todas características pertencentes ao Reino de Portugal desde o início da Era Moderna. Os portugueses se tornaram pioneiros da exploração marítima, desenvolvendo a rota comercial marítima entre a Europa e as Índias, passando por baixo do continente africano. Isso gerou um enriquecimento absurdo para Portugal, que se tornou o único provedor de especiarias do oriente por um preço competitivo durante um certo período. Depois com a chegada dos europeus na América, as colônias brasileiras exportaram várias mercadorias de alto valor desde o pau-brasil, chegando ao açúcar, até o ouro. Assim, a capital dos portugueses, Lisboa, se expandiu de maneira extraordinária. Além da expansão, o padrão da cidade era altíssimo com casas de cinco andares e mercados luxuosos por toda a cidade. Por um tempo ela era a principal cidade portuária e mercantil da Europa no aspecto de mercadorias luxuosas. Esse auge e era de ouro da cidade só foi acabar muito tempo depois, primeiramente com o início da União Ibérica e a subjugação de portugal a coroa espanhola, que também acabou com o monopólio portugues e holandes do açúcar. O último prego no caixão foi muito tempo depois com o terremoto de 1755, que devastou a cidade completamente.'
}

export const revIndustrialText = {
    pageOne1: 'No século XVIII, a invenção de máquinas como a locomotiva a vapor e o tear mecânico iniciou a Revolução Industrial, que foi um dos senão o evento histórico mais importante para a urbanização da Europa e do mundo. As cidades passaram de ser apenas centros comerciais para centros industriais também, proporcionando um crescimento absurdo. Grande parte da população rural se  moveu para as cidades em busca das oportunidades da vida urbana, só que foi uma migração tão grande e tão rápida que  as cidades não conseguiram aguentar o fluxo de pessoas.  Elas tinham fábricas muito sujas espalhadas por toda cidade ao lado de residências extremamente compactas de condições questionáveis.',
    pageOne2: ' As condições urbanas nunca tinham chegado nem perto de boas, já que as cidades Europeias não eram nada sanitárias, mas na Revolução Industrial tudo era muito pior com ruas imundas e epidemias constantes. Essa revolução se iniciou na Inglaterra, pois ela tinha a combinação de fatores perfeita para a industrialização, mas logo foi se espalhando para países que também possuíam esses fatores. Esses fatores eram, reservas energéticas de carvão mineral, reservas de ferro, burguesia forte e ideias iluministas fortes. Foi a partir daqui que o capitalismo começou a surgir, e a sociedade moderna começou a se estruturar com mais liberdades a partir de pensadores iluministas.',
    pageTwo: 'Nenhum exemplo é melhor do que a principal cidade inglesa, Londres. Ela já possuía uma boa relevância antes da Revolução Industrial, pois a Inglaterra já era um império colonial respeitável. Porém, foi a industrialização que a catapultou para se tornar a primeira superpotência do mundo, por consequência Londres também se tornou a maior cidade do planeta. Se as condições de uma cidade no início da revolução industrial eram ruins, Londres era pior ainda pela enorme massa de pessoas que viviam lá. Todo o “sucesso” dessa cidade tem relação com o “sucesso” de seu país, que criou o maior império colonial do mundo. Desde Austrália, até a Índia, passando pelo Egito e chegando até o Canadá, era um ditado que “o sol nunca se põe no império britânico". Todos esses recursos extraídos de colônias eram essenciais para a industrialização não só de Londres mas para toda a Grã-Bretanha. O auge desse imperialismo foi visto na Partilha da África, no qual potências europeias dividiram a África inteira entre eles sem consentimento nenhum dos africanos. A Grã-Bretanha obviamente ficou com a maior parcela de terras.'
};

export const secXXText = {
    pageOne: 'Na chegada do século XX, a Grã-Bretanha ainda era a grande potência mundial, enquanto a Europa era comparável a um barril de pólvora, já que o balanço de poder estava desequilibrado com a formação do Estado alemão e italiano. Com um sentimento nacionalista muito forte, estorou a primeira guerra mundial, a grande guerra, entre a Triplice Aliança e a Triplice Entente. A guerra foi a pior e mais devastadora que o mundo já tinha visto e a Europa se encontrou em ruínas. Com o enfraquecimento da Europa, uma nova superpotência surgiu, os Estados Unidos da América. Eles estavam no lado vencedor da guerra, porém por terem o Oceano Atlântico separando suas terras do combate, eles saíram da guerra e entraram em um período de prosperidade absurda, conhecido como Roaring Twenties. Assim, a concentração de espaços urbanos se desloca para o oeste com novos centros como Chicago, Nova Iorque e San Francisco. Nessa época, as cidades também já estavam muito mais modernas, com estradas para o carro a combustão e energia elétrica. O boom de prosperidade acaba com a quebra da Bolsa de Valores de Nova Iorque e a Grande Depressão, mas a posição dos EUA como superpotência já estava solidificada. A ascensão de regimes totalitários após a Crise de 29 na Europa causou a Segunda Guerra Mundial, desta vez entre Aliados e o Eixo. A conclusão deixou a Europa arrasada novamente, com os EUA vitoriosos no outro lado do oceano, mas desta vez com um rival para a posição de única superpotência mundial, a URSS.',
    pageTwo: 'Fundada como uma colônia holandesa, Nova Iorque se tornou a maior cidade dos EUA, sendo o principal centro comercial, informacional, financeiro e cultural da nação. No início do século XX, pequenos arranha-céus já começaram a surgir, sendo apenas uma amostra do horizonte completamente dominado pelos arranha-céus de hoje. Na época, além de cidade importante, Nova Iorque era o portão de entrada dos EUA para todos os imigrantes vindos do Atlântico, tanto que transformaram a Ilha Ellis, na foz do rio Hudson, em um checkpoint de imigrantes. Milhares passavam pela ilha todos os dias antes de chegar no continente, alguns tendo que ficar nela por dias. Nos Roaring Twenties, Nova Iorque era o grande centro cultural do mundo, sendo o local de origem do principal movimento musical da época, o Jazz. Além da música, o teatro era e ainda é fortíssimo na cidade com a famosa Broadway. A própria Grande Depressão começou em Nova Iorque com a quebra da bolsa de valores, que é umas das principais do mundo até hoje. Enfim, a cidade já foi a mais influente do mundo, e apesar de não ter a mesma hegemonia hoje, ainda é muito relevante.'
};

export const guerraFriaText = {
    pageOne: 'Após o desfecho da Segunda Guerra Mundial, duas superpotências de ideologias opostas surgiram lutando pela hegemonia de sua ideologia. Assim, o mundo se dividiu em dois e deu-se o início da Guerra Fria, já que nunca houve uma declaração de guerra entre as duas potências. Do lado ocidental, os EUA dominavam com a OTAN e influência sobre a América do Norte e Europa Ocidental, já do lado oriental, a URSS mandava com o Pacto de Varsóvia sobre o leste europeu. O contraste cultural entre os dois lados era imenso e isso afetou os espaços urbanos do mundo. Os países socialistas tinham controle total sobre as atividades econômicas e o planejamento das cidades, e por isso as cidades do bloco sovietico tinham muitos prédios idênticos e quadrados em comunidades extremamente padronizadas. Já as cidades do bloco capitalista tinham uma forma muito mais livre e prédios que também variavam dependendo da cultura local. Além de afetar a aparência das cidades, essa diferença cultural afetava o dia a dia que nas socialistas era muito mais controlado e “sem cor” comparado as capitalistas que eram caóticas e barulhentas. Nessa época, as cidades já estavam na forma que conhecemos hoje, e as redes urbanas estavam se conectando com rodovias e ferrovias modernas. O fenômeno da globalização começou a surgir, conectando os grandes centros urbanos do mundo. Todas as culturas começaram a se espalhar e a informação passou a demorar no máximo alguns poucos dias para chegar à população. Voos comerciais começaram a se tornar mais acessíveis, fazendo com que trajetos normalmente muito demorados fossem completados em horas. A tecnologia melhorou muito também com a corrida espacial nos anos 60 e a invenção da internet, que hoje é essencial para absolutamente tudo.',
    pageTwo: 'Nenhuma cidade consegue captar o espírito da Guerra Fria melhor que Berlim, uma cidade dividida no meio entre oeste e leste. Após a Segunda Guerra, a Alemanha foi dividida em quatro zonas de ocupação entre os EUA, França, Reino Unido e URSS e a capital foi dividida da mesma forma. Os territórios norte-americanos, franceses e britânicos se juntaram para formar a Alemanha Ocidental, enquanto os territórios da URSS formaram a Alemanha Oriental. A diferença entre as duas Alemanhas e Berlins era, e em alguns casos ainda é, muito perceptível, principalmente após o Muro de Berlim ser erguido, que isolou os dois lados completamente. Hoje ainda é possível perceber as divisões em imagens de satélite, nas quais a iluminação das ruas tem tonalidade diferente e até no esporte, já que os melhores times de futebol são da Alemanha Ocidental. Até o muro cair, ele separou centenas de famílias e impediu completamente o trânsito entre o oeste e leste com a intenção de impedir a migração de alemães do leste para o oeste. Berlim e o muro eram os maiores símbolos da guerra fria, já que tinham os dois opostos ideológicos vivendo em proximidade absurda. A relevância do muro era tanta que sua queda marcou o fim da Guerra Fria e a unificação das duas Alemanhas.'
}

export const atualidadeText = {
    pageOne: 'Com o fim da Guerra Fria e o colapso da URSS, os EUA saem vitoriosos e se encontram como hegemônicos novamente, porém novas potências menores surgem na Ásia. Assim, junto com o boom populacional asiatico, o balanço dos grandes centros urbanos rapidamente se desloca para o Leste Asiatico. Dentre os países que surgiram como novas pequenas e grandes potências estão o Japão, China, os tigres asiáticos e mais recentemente os novos tigres asiáticos. Estes países se tornam importantes centros industriais, e hoje a grande maioria dos produtos produzidos no mundo vem de algum desses países. O Japão tem seu crescimento atribuído principalmente a medidas pós Segunda Guerra que modernizaram a indústria e fizeram dele um centro de indústrias de alta tecnologia. Outra característica desse país e da maioria dos outros é o investimento pesado na educação para a formação de mão de obra extremamente qualificada. Isso tudo também normalmente é provocado por uma falta de recursos naturais para serem explorados. Apenas a China é um pouco diferente por ter crescido pela abertura de sua economia, que antes era completamente fechada, e sua enorme população. Além disso, a globalização também chega ao seu potencial quase completo com a popularização da internet, possibilitando comunicação instantânea global. Hoje fazemos praticamente tudo pela internet, e com a pandemia de COVID-19, fomos forçados ainda mais para esse meio.',
    tigres: ['Taiwan', 'Hong Kong', 'Coreia do Sul', 'Singapura'],
    novosTigres: ['Malásia', 'Indonésia', 'Tailândia', 'Vietnã', 'Filipinas'],
    pageTwo: 'Taipé é a capital da República da China, também conhecida como Taiwan, localizada no norte da Ilha de Formosa. Esse país é o Estado chinês que perdeu a Guerra Civil Chinesa, e foi exilado para Formosa, tendo tendência mais capitalista que a China comunista vencedora da guerra civil. Hoje a cidade é um dos senão o mais importante centro de indústrias altamente tecnológicas do mundo, sendo sede de empresas como ASUS, TSMC, D-Link e MSI. A cidade é dividida entre os municípios de Nova Taipé e Taipé, que é um enclave e o crescimento delas está diretamente relacionado ao crescimento de Taiwan, que seguiu o padrão geral dos tigres asiáticos, isso é, eles não tinham muitos recursos naturais na ilha, logo investiram muito em educação e abriram a economia. Assim, a cidade teve muito investimento externo, podendo desenvolver uma boa infraestrutura, que hoje é utilizada para fabricação de principalmente chips de computador, eletrônicos, equipamentos de precisão e até alimentos. O estilo da cidade é muito interessante por ter aspectos tradicionais da cultura chinesa, mas também ser pesadamente influenciada pela cultura ocidental. Esse é um tema geral para todas essas grandes cidades Asiáticas, que tem uma mistura de prédios tradicionais e arranha-céus de vidro gigantescos.'
};

export const glossario = {
    keys: ['Revolução Agrícola', 'Feudalismo (Europeu)', 'Feudos', 'Mercantilismo', 'Rota das especiarias', 'Queda de Constantinopla', 'Iluminismo', 'Burguesia', 'Imperialismo', 'Partilha da África', 'Guerra Fria', 'Tigres Asiáticos', 'Revolução Industrial', 'Globalização', 'Focos urbanos'],
    content: ['Momento na pré-história em que o homem se sedentarizou com o uso da agricultura.', 'Sistema hierárquico que surgiu na Idade Média, causando a descentralização dos grandes reinos e o surgimento dos feudos.', 'Núcleos do sistema feudal Europeu com um senhor feudal controlando servos para a agricultura.', 'Práticas econômicas desenvolvidas na Europa entre os séculos XV e XVIII fundamentadas no intervencionismo estatal, colonialismo, e metalismo.', 'Rotas comerciais entre o Oriente e a Europa para o comércio de especiarias que eram muito valorizadas no Ocidente.', 'Tomada da cidade de Constantinopla pelos turcos Otomanos causando a queda do Império Bizantino.', 'Corrente de ideias liberais na Europa que iam contra o antigo regime, com ênfase em John Locke que trouxe as ideias de origem do capitalismo.', 'Classe social vinda dos burgos, inicialmente formada por comerciantes que “escapavam” do sistema feudal.', 'Conjunto de ideais (principalmente da Europa) justificando e incentivando a expansão territorial de uma nação.', 'Reivindicações europeias sobre o continente Africano que o distribuiu quase completamente para as potências europeias.', 'Conflito entre os EUA e a URSS que envolveu vários outros conflitos diretos com apoio indireto das grandes potências.', 'Países asiáticos que sofreram rápida industrialização após a segunda guerra mundial.', 'Momento da introdução das máquinas na sociedade gerando uma revolução na economia e o amadurecimento do capitalismo.', ' Processo de encurtamento prático de distâncias no mundo causando maior comunicação entre diferentes países.', 'Lugares foco de urbanização em uma época, lugares com as maiores cidades da época.']
}








